### PR TITLE
Modified ReadMe.md to show TechEd Europe 2014 Video

### PR DESCRIPTION
**Pull request by fabianwilliams-zz**
Session at TEE2014 video link included in ReadMe.md file

### CODE REVIEW

**Comment by fabianwilliams-zz** [comment]
removed all references to my forked work, just readme.md file has modified content now.

**Comment by paulbatum** [comment]
Hi Fabian, I think you are having some problems, is this your first pull request? Look at the files changed list, you'll see this pull request still has several changes in it.

**Comment by paulbatum** [comment]
Try creating a new branch from my master and making the readme change there, pushing that as a new branch to your fork and sending the pull request from that.

**Comment by fabianwilliams-zz** [comment]
Yep I'll do that, thanks for replying 

Sent from my mobile device

## 4give any Miz-Spelln plz

…”Quinon Proficit Deficit”
//yes…this below will compile
public static void FabianGWilliams ()
{ 
     string company,phone,email,blog,twitter;
     company = “FabiansWorld “;
     phone = “202.670.2382 “;
     email = “fabian@fabiansworld.com” ;
     blog = “http://www.fabiangwilliams.com”;
     twitter = “@fabianwilliams” ;
}

**Pull request closed without merging**
